spring:
  application:
    name: gateway
  cloud:
    failFast: true
logging:
  file:
    name: gateway-console.log
ribbon:
  ReadTimeout: 10000
  ConnectTimeout:  10000

  eureka:
    enabled: true
#this is because on my local mac the host name is weird and doesn't resolve correctly so I get timeouts
#might be a DNS issue
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

zuul:
  debug:
    request: true
  routes:
      renderer:
        path: /renderer/**
        #url: http://localhost:8080/
        serviceId: renderer
      #gsrs:
       # sensitiveHeaders:
       # path: /ginas/app/**
       # stripPrefix: false
       # url: http://localhost:9000/

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

